name: Veracode_Container_scan
on:
  push:
    branches: [ master ]

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: pipeline


    steps:
      # - name: checkout repo
      #   uses: actions/checkout@v3



      - name: Verracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "json"
          debug: false
          fail_build: false
